NUM_USERS = 4         # (edge users)
X_LENGTH = 500        # m (horizontal length of area)
Y_LENGTH = 500        # m (vertical length of area)

DOPPLER_FREQ = 10
NOISE_STD = -174      # AWGN (dBm/Hz)
FADE_STD = 4          # path loss noise (dB)
B = 1e6               # bandwidth (Hz)
P_MAX = 24            # max power (dBm)
C = 50                # computational power (CPU cycles/bit)
C_COEFF = 10**(-28)   # effective capacitance coefficient
FREQUENCY = 6e6       # local CPU frequency (Hz)
T_MAX = 0.1           # timeslot duration (sec)
DATA_SIZE = 1e6       # base size of users' tasks (CPU cycles)

STATE_DIM = 3         # bs_channel, eve_channel, task_size
ACTION_DIM = 3        # p1, p2, task_size_ratio
EPISODES = 5000
TIMESLOTS = 300
EPISODES_BEFORE_TRAIN = 10
BETA = 10             # number of steps required to update local networks
CAPACITY = 2e6        # memory size
BATCH_SIZE = 32
SCALE_REWARD = 1
GAMMA = 0.99          # discount factor
TAU = 1e-5            # soft update constant
ACTOR_LR = 1e-5       # actor learning rate
CRITIC_LR = 1e-4      # critic learning rate
RATE_MIN = 1.5 * DATA_SIZE / (C * T_MAX * B)
PATH = '/home/michalakos/Documents/Thesis/training_results'
